feat(spring boot): Upgrade spring boot dependency to 2.4.2
- replace spring-boot-test by spring-boot-starter-test to avoid NoClassDefFoundError with AopTestUtils on all unit tests
- remove assertj-core because it's include on spring-boot-starter-test